ApartmentBuildingManagementSystem/Models/ConsumptionDetails.cs
using Newtonsoft.Json;

namespace ApartmentBuildingManagementSystem.Models
{
    public enum ConsumptionType {
        HotWater,
        ColdWater,
        Electricity,
        Gas
    };

    /// <summary>
    /// Class for the details of any kind of consumption (electricity, gas, water)
    /// </summary>
    public class ConsumptionDetails
    {
        [JsonProperty(PropertyName = "id")]
        public Guid Id { get; set; }

        public DateTime DateCreated { get; set; }

        public ConsumptionType ConsumptionType { get; set; }

        public double Consumption { get; set; }

        public double Price { get; set; }
    }
}

ApartmentBuildingManagementSystem/Models/Consumptions.cs
namespace ApartmentBuildingManagementSystem.Models
{
    public class Consumptions
    {
        public Guid Id { get; set; }

        public DateTime DateCreated { get; set; }

        public List<Resident>? Residents { get; set; }
    }
}

ApartmentBuildingManagementSystem/Models/ErrorViewModel.cs
namespace ApartmentBuildingManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApartmentBuildingManagementSystem/Models/Resident.cs
namespace ApartmentBuildingManagementSystem.Models
{
    public class Resident
    {
        public Guid Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }

        public int ApartmentNumber { get; set; }

        public List<ConsumptionDetails>? ConsumptionDetails { get; set; }
    }
}

ApartmentBuildingManagementSystem/Controllers/ConsumptionController.cs
using ApartmentBuildingManagementSystem.Models;
using ApartmentBuildingManagementSystem.Services;
using Microsoft.AspNetCore.Mvc;

namespace ApartmentBuildingManagementSystem.Controllers
{
    public class ConsumptionController : Controller
    {
        private readonly ICosmosDbService _cosmosDbService;
        public ConsumptionController(ICosmosDbService cosmosDbService)
        {
            _cosmosDbService = cosmosDbService;
        }

        [ActionName("OverviewOfConsumptions")]
        public async Task<IActionResult> GetAll()
        {
            return View(await _cosmosDbService.GetItemsAsync("SELECT * FROM c"));
        }

        [ActionName("UploadConsumption")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("UploadConsumption")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("Id,DateCreated,ConsumptionType,Consumption,Price")] ConsumptionDetails cd)
        {
            if (ModelState.IsValid)
            {
                cd.Id = Guid.NewGuid();
                cd.DateCreated = DateTime.UtcNow;
                await _cosmosDbService.AddItemAsync(cd);
                return RedirectToAction("OverviewOfConsumptions");
            }

            return View(cd);
        }

        [HttpPost]
        [ActionName("EditConsumption")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync([Bind("Id,DateCreated,ConsumptionType,Consumption,Price")] ConsumptionDetails cd)
        {
            if (ModelState.IsValid)
            {
                await _cosmosDbService.UpdateItemAsync(cd.Id.ToString(), cd);
                return RedirectToAction("OverviewOfConsumptions");
            }

            return View(cd);
        }

        [ActionName("EditConsumption")]
        public async Task<ActionResult> EditAsync(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            ConsumptionDetails item = await _cosmosDbService.GetItemAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [ActionName("Details")]
        public async Task<ActionResult> DetailsAsync(string id)
        {
            return View(await _cosmosDbService.GetItemAsync(id));
        }
    }
}

ApartmentBuildingManagementSystem/Controllers/HomeController.cs
using ApartmentBuildingManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ApartmentBuildingManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApartmentBuildingManagementSystem/Views/Consumption/EditConsumption.cshtml
@model ApartmentBuildingManagementSystem.Models.ConsumptionDetails

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit consumption detail</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ConsumptionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ConsumptionType, new SelectList(Enum.GetValues(typeof(ConsumptionType))), "")
                @Html.ValidationMessageFor(model => model.ConsumptionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Consumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Consumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Consumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.TextBoxFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn-default" />
            </div>
        </div>
    </div>
}

<br />
<div>
    @Html.ActionLink("Back to List", "OverviewOfConsumptions")
</div>

<script src="~/bundles/jqueryval"></script>

ApartmentBuildingManagementSystem/Views/Consumption/OverviewOfConsumptions.cshtml
@model IEnumerable<ApartmentBuildingManagementSystem.Models.ConsumptionDetails>

@{
    ViewBag.Title = "OverviewOfConsumptions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of consumptions</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Consumption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ConsumptionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Consumption)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditConsumption", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Create New", "UploadConsumption")
</p>

ApartmentBuildingManagementSystem/Views/Consumption/UploadConsumption.cshtml
@model ApartmentBuildingManagementSystem.Models.ConsumptionDetails

@{
    ViewBag.Title = "UploadConsumption";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UploadConsumption</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Consumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Consumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Consumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "OverviewOfConsumptions")
</div>

ApartmentBuildingManagementSystem/Views/Home/Consumptions.cshtml
@{
    ViewData["Title"] = "Consumptions";
}
@Html.ActionLink("See the list of consumptions", "OverviewOfConsumptions")

ApartmentBuildingManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ApartmentBuildingManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApartmentBuildingManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApartmentBuildingManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Consumption" asp-action="OverviewOfConsumptions">Apartment Building Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ApartmentBuildingManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>